[package]
name = "openbas-agent"
version = "0.0.1"
edition = "2021"

[dependencies]
ureq = { version = "2.1", features = ["tls", "json"] }
config = "0.14.0"
serde = { version = "1.0.203", features = ["derive"] }
log = "0.4.21"
hostname = "0.4.0"
network-interface = "2.0.0"
signal-hook = "0.3.17"
base64 = "0.22.1"
mid = "2.0.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json"] }
