version: 2.1

orbs:
  win: circleci/windows@5.0

executors:
  docker:
    docker:
      - image: cimg/rust:1.78
  linux:
    machine: true
  macos:
    macos:
      xcode: 12.5.1

jobs:
  windows_build:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
            - cargo-{{ arch }}
      - run: choco install -y mingw nsis
      - run: curl.exe --output rustup-init.exe --url https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe
      - run: ./rustup-init.exe -vy
      - run: rustup toolchain install stable-x86_64-pc-windows-msvc
      - run: rustup default stable-x86_64-pc-windows-msvc
      - run: cargo build --release
      - run: $env:Path += "C:\Program Files (x86)\NSIS\Bin"; makensis ./installer/windows/installer.nsi
      - run: curl.exe -u samuel.hassine@filigran.io:$env:JFROG_TOKEN -T ./target/release/openbas-agent.exe "https://filigran.jfrog.io/artifactory/openbas-agent/openbas-agent-latest.exe"
      - run: curl.exe -u samuel.hassine@filigran.io:$env:JFROG_TOKEN -T ./installer/windows/openbas-agent-installer.exe "https://filigran.jfrog.io/artifactory/openbas-agent/openbas-agent-installer-latest.exe"
      - save_cache:
          key: cargo-{{ arch }}-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo

workflows:
  openbas-agent:
    jobs:
      - windows_build:
          filters:
            tags:
              only: /.*/